layout_spectrum: 0.6663941356819123
typography_spectrum: 0.032216868828982115
color:
  brandStrength: 0.9531497932039201
  lightness: 0.12771895923651755
  saturation: 0.9828771178144962
  rhythmicContrast: 0.07990375952795148
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
opengraph:
  type: ''
author:
  name: Ole Vik
  email: post@oslofelgretting.no
  url: www.oslofelgretting.no
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b742d476-e3cf-4791-9aa6-062bd2bfba3e.png
name: Oslo Felgretting AS
navigation:
  - name: Info
    id: f570d63a-74d1-448e-8373-3e636777f98a
    type: content
  - name: Priser
    id: 16165f06-22c1-459b-a273-5c98f0f733d1
    type: content
  - name: Dekk og felger
    id: a337a64f-beac-4658-bb06-8a9acc5218d3
    type: content
  - name: Kontakt oss
    id: 2addc55d-fd2e-4315-8613-5f4e09a89845
    type: content
title: Reparasjon og oppussing av felger
description: NÃ¥r service og erfaring teller
