typography_spectrum: 0.938331536250189
color:
  brandStrength: 0.18828413425944746
  lightness: 0.9140634832438082
  saturation: 0.5986697834450752
  rhythmicContrast: 0.15131006273441017
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
layout_spectrum: 0.7525188568979502
name: Oslo Felgretting
title: Når god service og lang erfaring teller
description: Når god service og lang erfaring teller
